name: asbool
description: Simple tool to convert whatever thing (dynamic) to a bool value.
version: 1.0.3
homepage: https://github.com/rsc1975/asbool

environment:
  sdk: '>=2.14.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  coverage: ^1.4.0


