name: asbool
description: Simple tool to convert whatever thing (dynamic) to a bool value.
version: 1.0.1
homepage: https://github.com/rsc1975/asbool

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
