name: GitHub Actions for asBool lib
on: [push]
jobs:
  Test-Coverage:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          cd ${{ github.workspace }}
      - uses: subosito/flutter-action@v2
        with:
      	  flutter-version: '2.x'
          channel: 'stable'
      - run: dart pub get       
      - run: dart analyze       
      - run: dart test --coverage=coverage -r github
      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}      
      - run: echo "🍏 This job's status is ${{ job.status }}."
